# Generated by Django 5.1.6 on 2025-02-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
